# NUMPY

In [ ]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

## Create array using Numpy

In [10]:
## 1D array
ar1=np.array([1,2,34,55])
print(ar1)
print(type(ar1))
ar1.shape


[ 1  2 34 55]
<class 'numpy.ndarray'>


(4,)

In [ ]:
## 2D array 
ar2=np.array([1,2,34,55])
ar2.reshape(1,4) ## 0ne row and 4 columns 

array([[ 1,  2, 34, 55]])

In [13]:
ar2=np.array([[1,2,34,55]])
ar2.shape

(1, 4)

In [ ]:
ar2=np.array([[1,2,34,55],[7,7,8,9]]) ## 2 rows and 4 columns 
print(ar2)
ar2.shape 

[[ 1  2 34 55]
 [ 7  7  8  9]]


(2, 4)