# NUMPY

In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

## Create array using Numpy

In [3]:
## 1D array
ar1=np.array([1,2,34,55])
print(ar1)
print(type(ar1))
ar1.shape


[ 1  2 34 55]
<class 'numpy.ndarray'>


(4,)

In [4]:
## 2D array 
ar2=np.array([1,2,34,55])
ar2.reshape(1,4) ## 0ne row and 4 columns 

array([[ 1,  2, 34, 55]])

In [5]:
ar2=np.array([[1,2,34,55]])
ar2.shape

(1, 4)

In [6]:
ar2=np.array([[1,2,34,55],[7,7,8,9]]) ## 2 rows and 4 columns 
print(ar2)
ar2.shape 

[[ 1  2 34 55]
 [ 7  7  8  9]]


(2, 4)

In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((3,4))
## all elemts will be one (3 row ,4 columns )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
## Identity Matrix 
# diogonial elements will be one 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Atributes of NUM py Array

In [10]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("Array:\n",arr)
print(arr.shape)
print(arr.ndim) ##  to see the dimension of the array
print(arr.size)
print(arr.dtype)
print(arr.itemsize)


Array:
 [[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
8
int64
8


# Numpy vectorized Operation


In [11]:
arr3=np.array([1,2,3,4])
arr4=np.array([11,22,32,42])
## elemnet wise addition 
print("addition :",arr3+arr4)

addition : [12 24 35 46]


In [12]:
## element wise substraction
print(arr3-arr4)

[-10 -20 -29 -38]


In [13]:
## multiplication
print(arr3*arr4)

[ 11  44  96 168]


In [14]:
## dev
print(arr3/arr4)

[0.09090909 0.09090909 0.09375    0.0952381 ]


# Universal Function 


In [15]:
arr=np.array([1,2,3,4])
## square root
print(np.sqrt(arr))
## exponential
print(np.exp(arr))
##  sine
print(np.sin(arr))
## natural log 
print(np.log(arr))




[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


# Array slicing and indexing

In [16]:
arr5=np.array([[1,2,3,4],[5,6,7,8],[11,22,33,44]])
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]]


In [17]:
arr5[0][0]

np.int64(1)

In [18]:
arr5[1][2]

np.int64(7)

In [19]:
arr5[1:,1:]

array([[ 6,  7,  8],
       [22, 33, 44]])

# modify array elements

In [20]:
arr5[0,0]=100
## arr5[1:]=100
print(arr5)

[[100   2   3   4]
 [  5   6   7   8]
 [ 11  22  33  44]]


# Statistical Cocept

In [21]:
# Normalization 
# to  have  a mean of 0 and standard deviation of 1

data=np.array([1,2,3,4,56])

# calculate the mean and standard deviation 
mean=np.mean(data)
print(mean)
stdandard_deviation= np.std(data)
print(stdandard_deviation)

##### Normalize data 
normalize_data= (data-mean)/stdandard_deviation
print(normalize_data)
## variance 
variance=np.var(data)
print(variance)

13.2
21.423351745233514
[-0.56947205 -0.52279401 -0.47611597 -0.42943794  1.99781997]
458.9599999999999


# Logical Operations

In [22]:
data>5
data[(data>5)] |(data<=8)

array([57, 57, 57, 57, 56])