# NUMPY

In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

## Create array using Numpy

In [3]:
## 1D array
ar1=np.array([1,2,34,55])
print(ar1)
print(type(ar1))
ar1.shape


[ 1  2 34 55]
<class 'numpy.ndarray'>


(4,)

In [4]:
## 2D array 
ar2=np.array([1,2,34,55])
ar2.reshape(1,4) ## 0ne row and 4 columns 

array([[ 1,  2, 34, 55]])

In [5]:
ar2=np.array([[1,2,34,55]])
ar2.shape

(1, 4)

In [6]:
ar2=np.array([[1,2,34,55],[7,7,8,9]]) ## 2 rows and 4 columns 
print(ar2)
ar2.shape 

[[ 1  2 34 55]
 [ 7  7  8  9]]


(2, 4)

In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))
## all elemts will be one (3 row ,4 columns )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
## Identity Matrix 
# diogonial elements will be one 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Atributes of NUM py Array

In [19]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("Array:\n",arr)
print(arr.shape)
print(arr.ndim) ##  to see the dimension of the array
print(arr.size)
print(arr.dtype)
print(arr.itemsize)


Array:
 [[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
8
int64
8
